name: package-macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]
        haxe: [4.2.4]
      fail-fast: true
    runs-on: macos-latest

    steps:
      # Checkout, install haxe and libs
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxe setup.hxml
      - run: haxelib list

      # Node/NPM commands
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd app && npm install
      - run: cd app && npm run pack-prepare
      - run: cd app && npm run pack-macos

      # Upload
      - uses: actions/upload-artifact@v2
        with:
          name: mac-distribution
          path: app/redist/LDtk**installer.dmg
