name: package-raspberry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.2.4]
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      # Checkout, install haxe and libs
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}

        # Snapcraft required for ARM build
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - run: haxe -version
      - run: haxe setup.hxml
      - run: haxelib list

      # Node/NPM commands
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd app && npm install
      - run: cd app && npm run pack-linux-arm64

      # Upload
      - uses: actions/upload-artifact@v2
        with:
          name: raspberry-distribution
          path: app/redist/LDtk**installer.AppImage
